server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: example
    url: jdbc:postgresql://localhost:5432/customer
    password: password
  zipkin:
    base-url: http://127.0.0.1:9411
  rabbitmq:
    addresses: localhost:5672
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
